import {
  type RouteConfig,
  index,
  layout,
  route,
} from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("login", "routes/Login.tsx"),
  // you can use index or layout for nested routes
  layout("routes/protected/layout.tsx", [
    route("dashboard", "routes/protected/Dashboard.tsx"),
    route("admins", "routes/protected/Admins.tsx"),
    route("doctors", "routes/protected/Doctors.tsx"),
    route("nurses", "routes/protected/Nurses.tsx"),
    route("patients", "routes/protected/Patients.tsx"),
    route("activities-log", "routes/protected/ActivitiesLog.tsx"),
    route("profile/:id", "routes/protected/Profile.tsx"),
    route("my-billing", "routes/protected/MyBilling.tsx"),
    route("financial-history", "routes/protected/FinancialHistory.tsx"),
    route("nursing", "routes/protected/NursingStation.tsx"),
    route("pharmacy", "routes/protected/pharmacy/PharmacyDashboard.tsx"),
    route("pharmacy/dispense", "routes/protected/pharmacy/Dispense.tsx"),
    route("pharmacy/inventory", "routes/protected/pharmacy/Inventory.tsx"),
    route("pharmacy/prescriptions", "routes/protected/pharmacy/Prescriptions.tsx"),
    route("lab", "routes/protected/lab/LabDashboard.tsx"),
    route("lab/requests", "routes/protected/lab/TestRequests.tsx"),
    route("lab/results", "routes/protected/lab/ResultsEntry.tsx"),
    route("records", "routes/protected/FinancialRecords.tsx"),
    route("appointments", "routes/protected/Appointments.tsx"),
    route("telemedicine", "routes/protected/Telemedicine.tsx"),
    route("settings", "routes/protected/settings/SettingsLayout.tsx", [
      index("routes/protected/settings/SettingsIndex.tsx"),
      route("general", "routes/protected/settings/GeneralSettings.tsx"),
      route("roles", "routes/protected/settings/RoleManagement.tsx"),
      route("security", "routes/protected/settings/SecuritySettings.tsx"),
      route("notifications", "routes/protected/settings/NotificationSettings.tsx"),
      route("email", "routes/protected/settings/EmailSettings.tsx"),
      route("billing", "routes/protected/settings/BillingSettings.tsx"),
      route("appointments", "routes/protected/settings/AppointmentSettings.tsx"),
      route("lab", "routes/protected/settings/LabSettings.tsx"),
      route("pharmacy", "routes/protected/settings/PharmacySettings.tsx"),
      route("system", "routes/protected/settings/SystemPreferences.tsx"),
      route("audit-logs", "routes/protected/settings/AuditLogs.tsx"),
      route("backup", "routes/protected/settings/BackupRestore.tsx"),
      route("integrations", "routes/protected/settings/Integrations.tsx"),
      route("ai", "routes/protected/settings/AIConfig.tsx"),
      route("profile", "routes/protected/settings/ProfileSettings.tsx"),
    ]),
  ]),
  route("*", "routes/NotFound.tsx"),
] satisfies RouteConfig;
